version: '3'
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
services:
  dbsql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Test1234@
    ports:
      - '1433:1433'
    networks:
      - backend
    container_name: database
  videoapi:
    image: aesir1/videocore:5
    ports:
      - '8080:80'
    networks:
      - frontend
      - backend
    environment:
      - ConnectionStrings__DefaultConnection=Server=dbsql,1433;Database=VIDEOTHEKCore;Integrated Security=false;User ID=SA;Password=Test1234@;
      - ASPNETCORE_URLS=http://+:80
    container_name: backend
    depends_on:
      - dbsql
    restart: always
  reactfront:
    image: aesir1/reactapp:1.0
    ports:
      - '3000:3000'
    networks:
      - frontend
    container_name: ui
    depends_on:
      - videoapi